name: k8s_client
version: 1.0.0
description: Dart Kubernetes Client API
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  k8s_api:
    path: ./k8s_api
  openapi_dart_common: ^3.1.0
  dio: ^3.0.9
  yaml: ^2.2.1
  logging: ^0.11.4

dev_dependencies:
  test: ^1.3.0
